# CountVectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

documents = ["가나다 마바사", "에비씨 디이에프"]

vectorizer = CountVectorizer()
vectorizer.fit_transform(documents)



<2x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

# numpy 설명

In [1]:
import numpy as np
v1 = np.array([[1, 1, 0, 0, 0], 
               [1, 1, 0, 0, 0]])

np.sum(v1, axis=1)

array([2, 2])

In [2]:
import numpy as np
v1 = np.array([[1, 1, 0, 0, 0], 
               [1, 1, 0, 0, 0]])

np.sum(v1, axis=0)

array([2, 2, 0, 0, 0])

In [3]:
import numpy as np
v1 = np.array([[1, 1, 0, 0, 0], 
               [1, 1, 0, 0, 0]])


np.sum(v1, axis=1).shape

(2,)

In [4]:
v1.shape

(2, 5)

In [5]:
np.sum(v1, axis=0)

array([2, 2, 0, 0, 0])

In [6]:
np.sum(v1, axis=0, keepdims=True)

array([[2, 2, 0, 0, 0]])

In [7]:
np.sum(v1, axis=0, keepdims=True).shape

(1, 5)

In [8]:
np.sum(v1, axis=1, keepdims=True)

array([[2],
       [2]])

In [9]:
np.sum(v1, axis=1).shape

(2,)

In [10]:
x1 = np.sum(v1, axis=1, keepdims=True)
x2 = np.sum(v1, axis=0, keepdims=True)

In [11]:
x1

array([[2],
       [2]])

In [12]:
x2

array([[2, 2, 0, 0, 0]])

In [13]:
x1+x2

array([[4, 4, 2, 2, 2],
       [4, 4, 2, 2, 2]])

In [14]:
v1 = np.array([[1, 1, 0, 0, 0], 
               [1, 1, 0, 0, 0]])

v2 = np.array([[1, 0, 1, 1, 0],
               [0, 1, 1, 1, 0],
               [0, 1, 1, 1, 0]])

def jaccard_similarity(v1, v2):
    m = np.dot(v1, v2.T)
    s = np.sum(v1, axis=1, keepdims=True) + np.sum(v2.T, axis=0, keepdims=True) - m
    return m/s

jaccard_similarity(v1, v2)

array([[0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25]])

In [15]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(v1, v2)

array([[0.40824829, 0.40824829, 0.40824829],
       [0.40824829, 0.40824829, 0.40824829]])

In [16]:
np.sum(v1, axis=1, keepdims=True) + np.sum(v1.T, axis=0, keepdims=True)

array([[4, 4],
       [4, 4]])

In [17]:
v2 = np.array([[1, 0, 1, 1, 0],
            [0, 1, 1, 1, 0],
            [0, 1, 1, 1, 0]])

In [18]:
v2.T

array([[1, 0, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0]])

In [19]:
text = "황량한 사막 위의 병사"

In [20]:
text.split()

def SubstringTokenizer(text):
  return [t[:2] for t in text.split() if len(t) > 1]

SubstringTokenizer(text)

['황량', '사막', '위의', '병사']